# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1, 2, 3, 4, 5])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1, 2.0, 3.0, 4.1], [2.1, 3.1, 4.1, 6.1]])
arr1, arr2

(array([1, 2, 3, 4, 5]),
 array([[1. , 2. , 3. , 4.1],
        [2.1, 3.1, 4.1, 6.1]]))

In [4]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
arr1.shape, arr1.ndim, arr1.dtype, arr1.size, type(arr1)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
arr2.shape, arr2.ndim, arr2.dtype, arr2.size, type(arr2)

((2, 4), 2, dtype('float64'), 8, numpy.ndarray)

In [7]:
# Create an array of shape (5, 5) with only ones
ones = np.ones([5,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# Create an array of shape (3, 3, 5) with only zeros
zeroes = np.zeros((3,3,5))
zeroes

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array_random = np.random.randint(10, size=(7,2))
array_random

array([[2, 6],
       [5, 8],
       [8, 9],
       [5, 4],
       [6, 0],
       [5, 0],
       [2, 6]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
float_random = np.random.rand(3,5)
float_random

array([[0.10585435, 0.58855037, 0.309764  , 0.69619181, 0.49575082],
       [0.72063165, 0.70563649, 0.24345893, 0.18020283, 0.70966138],
       [0.36476661, 0.11099981, 0.56037467, 0.40579957, 0.97334534]])

In [12]:
# Create an array of normally distributed random numbers
normal_distributed = np.random.randn(5, 3)
normal_distributed

array([[ 0.26287848,  0.33279796, -0.73546377],
       [ 0.30295903,  0.75322286, -0.78572922],
       [-0.41731706, -1.10742824, -0.05088008],
       [ 1.53905081,  0.13982182, -1.58297233],
       [ 0.26537743, -0.95493597, -0.4042916 ]])

In [13]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array = np.random.randint(10, size=(4,6))
random_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [14]:
# Copy the code from the cell above and run it again
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array = np.random.randint(10, size=(4,6))
random_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [15]:
# Find the 0'th index of the latest array you created
random_array[0]

array([6, 3, 7, 4, 6, 9])

In [21]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

In [25]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2,:2]

array([[6, 3],
       [2, 6]])

In [26]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
array_1 = np.random.randint(10, size=(3,5))

array_2 = np.ones([3,5])

array_1, array_2

(array([[8, 0, 9, 2, 6],
        [3, 8, 2, 4, 2],
        [6, 4, 8, 6, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [27]:
# Add the two arrays together
sum = array_1 + array_2
sum

array([[ 9.,  1., 10.,  3.,  7.],
       [ 4.,  9.,  3.,  5.,  3.],
       [ 7.,  5.,  9.,  7.,  2.]])

In [28]:
# Create another array of ones of shape (5, 3)
ones_array = np.ones([5,3])
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
sum + ones_array

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [32]:
# Do the same operation you just did but this time with a transpose on one array
ones_array = ones_array.T
sum = sum + ones_array
sum

array([[10.,  2., 11.,  4.,  8.],
       [ 5., 10.,  4.,  6.,  4.],
       [ 8.,  6., 10.,  8.,  3.]])

In [33]:
# Take the latest array to the power of 2 using the python way
sum ** 2

array([[100.,   4., 121.,  16.,  64.],
       [ 25., 100.,  16.,  36.,  16.],
       [ 64.,  36., 100.,  64.,   9.]])

In [36]:
# Do the same thing with numpy way
np.power(sum, 2)

array([[100.,   4., 121.,  16.,  64.],
       [ 25., 100.,  16.,  36.,  16.],
       [ 64.,  36., 100.,  64.,   9.]])

In [38]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
np.mean(sum), np.min(sum), np.max(sum), np.std(sum), np.var(sum)

(6.6, 2.0, 11.0, 2.8000000000000003, 7.840000000000002)

In [39]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
a1 = np.random.randint(10, size=(3,3))
a2 = np.random.randint(10, size=(3,2))
a1, a2

(array([[3, 8, 1],
        [9, 8, 9],
        [4, 1, 3]]),
 array([[6, 7],
        [2, 0],
        [3, 1]]))

In [40]:
# Perform a dot product on the two newest arrays you created
np.dot(a1, a2)

array([[37, 22],
       [97, 72],
       [35, 31]])

In [41]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
a1 = np.random.randint(10, size=(4,3))
a2 = np.random.randint(10, size=(4,3))
a1, a2

(array([[7, 3, 1],
        [5, 5, 9],
        [3, 5, 1],
        [9, 1, 9]]),
 array([[3, 7, 6],
        [8, 7, 4],
        [1, 4, 7],
        [9, 8, 8]]))

In [42]:
# Perform a hadamard product on the two newest arrays you created
a1 * a2

array([[21, 21,  6],
       [40, 35, 36],
       [ 3, 20,  7],
       [81,  8, 72]])

In [43]:
# Perform a dot product on the two newest arrays you created # Error anticipated
np.dot(a1, a2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [44]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
a1 = a1.T
np.dot(a1, a2)

array([[145, 168, 155],
       [ 63,  84,  81],
       [157, 146, 121]])

In [45]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
a1 = np.random.randint(10, size=(4,3))
a2 = np.random.randint(10, size=(4,3))
a1, a2

(array([[0, 8, 6],
        [8, 7, 0],
        [7, 7, 2],
        [0, 7, 2]]),
 array([[2, 0, 4],
        [9, 6, 9],
        [8, 6, 8],
        [7, 1, 0]]))

In [46]:
# Compare the two arrays with '>', '<=' and '==' 
a1>a2, a1<=a2, a1==a2

(array([[False,  True,  True],
        [False,  True, False],
        [False,  True, False],
        [False,  True,  True]]),
 array([[ True, False, False],
        [ True, False,  True],
        [ True, False,  True],
        [ True, False, False]]),
 array([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]]))

In [47]:
# Sort one of the arrays you just created in ascending order
np.sort(a1)

array([[0, 6, 8],
       [0, 7, 8],
       [2, 7, 7],
       [0, 2, 7]])

In [48]:
# Sort the indexes of one of the arrays you just created
np.argsort(a1)

array([[0, 2, 1],
       [2, 1, 0],
       [2, 0, 1],
       [0, 2, 1]])

In [49]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a1)

1

In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100
a3 = np.linspace(1, 100, 10)
a3

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [51]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(a3)

9

In [52]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(a3)

0